### ISSUE TITLE
File error, help wantet

### ISSUE THREAD

**Issue by Kasp521j** [shaneMenzies/BaronyPA#1]
@shaneMenzies 

The downloaded file is not a "plugin" when trying to add it to Mumble

help please?

![image](https://github.com/shaneMenzies/BaronyPA/assets/143341516/ec7d5b22-f7f9-467b-b59f-7f4d1f861933)

**Comment by shaneMenzies** [comment]
try the newest release,[ v0.1.3](https://github.com/shaneMenzies/BaronyPA/releases/tag/v0.1.3)

**Comment by Kasp521j** [comment]
> try the newest release,[ v0.1.3](https://github.com/shaneMenzies/BaronyPA/releases/tag/v0.1.3)

Thank you, This seemed to work, funny enough we could not find that update yesterday, but yea now new problems emerge (the same as the one in the other thread)
