### ISSUE TITLE
The Plugin does not seem to recognize the EPIC GAMES version of Barony

### ISSUE THREAD

**Issue by popdoo323-pop** [shaneMenzies/BaronyPA#2]
My friend was not able to recognize it
I was able to connect but they weren't able to. (maybe it's because I used Steam)
This is all I could provide
![image](https://github.com/shaneMenzies/BaronyPA/assets/85776019/a86ce751-ceb2-4caa-a4b5-3e009b6358e1)

**Comment by Kasp521j** [comment]
i seem to have the same problem, it won't recognize that I have opened the game through Epic games

**Comment by shaneMenzies** [comment]
The current version won't work with the Epic version, someone would need to decompile the Epic Games version to find the correct settings, and I only have the Steam version.
